export { default as ArrowBack } from './arrow-back.svg?react'
export { default as Bank } from './bank.svg?react'
export { default as Bus } from './bus.svg?react'
export { default as ChevronLeft } from './chevron-left.svg?react'
export { default as Coffee} from './coffee.svg?react'
export { default as Grid } from './grid.svg?react'
export { default as MoneyBag } from './money-bag.svg?react'
export { default as Store } from './store.svg?react'
export { default as Wallet } from './wallet.svg?react'
export { default as Home } from './home.svg?react'
export { default as Calendar } from './calendar.svg?react'
export { default as Wallet2 } from './wallet-2.svg?react'
export { default as User } from './user.svg?react'
export { default as Plus } from './plus.svg?react'
export { default as More } from './more.svg?react'
